In [ ]:
# Importing Libraries
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
my_file = '/content/drive/My Drive/Aly/Uber_Data/uber_data.csv'

In [ ]:
df = pd.read_csv(my_file)

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  object
 2   tpep_dropoff_datetime  100000 non-null  object
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.5+ MB

In [ ]:
#Converting object to datetime
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [ ]:
df = df.drop_duplicates().reset_index(drop=True)
df['trip_id'] = df.index

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  datetime64[ns]
 2   tpep_dropoff_datetime  100000 non-null  datetime64[ns]
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
 19  trip_id                100000 non-null  int64
dtypes: datetime64[ns](2), float64(12), int64(5), object(1)
memory usage: 15.3+ MB

In [ ]:
# Altering/Creating our datetime dimension table
datetime_dim = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].drop_duplicates().reset_index(drop=True)
datetime_dim['pickup_hour'] = datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['pickup_day'] = datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pickup_month'] = datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pickup_year'] = datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pickup_weekday'] = datetime_dim['tpep_pickup_datetime'].dt.weekday

datetime_dim['dropoff_hour'] = datetime_dim['tpep_dropoff_datetime'].dt.hour
datetime_dim['dropoff_day'] = datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['dropoff_month'] = datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['dropoff_year'] = datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['dropoff_weekday'] = datetime_dim['tpep_dropoff_datetime'].dt.weekday

In [ ]:
datetime_dim['datetime_id'] = datetime_dim.index

In [ ]:
datetime_dim = datetime_dim[['datetime_id','tpep_pickup_datetime','pickup_hour','pickup_day','pickup_month','pickup_year','pickup_weekday','tpep_dropoff_datetime','dropoff_hour','dropoff_day','dropoff_month','dropoff_year','dropoff_weekday']]

In [ ]:
datetime_dim

,datetime_id,tpep_pickup_datetime,pickup_hour,pickup_day,pickup_month,pickup_year,pickup_weekday,tpep_dropoff_datetime,dropoff_hour,dropoff_day,dropoff_month,dropoff_year,dropoff_weekday
0,0,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01 00:00:01,0,1,3,2016,1,2016-03-01 00:16:04,0,1,3,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99848,99848,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:15,6,1,3,2016,1
99849,99849,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:32:41,6,1,3,2016,1
99850,99850,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:37:23,6,1,3,2016,1
99851,99851,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:09,6,1,3,2016,1
99852,99852,2016-03-01 06:17:11,6,1,3,2016,1,2016-03-01 06:22:00,6,1,3,2016,1

In [ ]:
trip_distance_dim = df['trip_distance'].drop_duplicates().reset_index(drop=True)

In [ ]:
trip_distance_dim = trip_distance_dim.to_frame(name='trip_distance')

In [ ]:
trip_distance_dim['trip_distance_id'] = trip_distance_dim.index

In [ ]:
trip_distance_dim.dtypes

trip_distance_id      int64
trip_distance       float64
dtype: object

ValueError: setting an array element with a sequence.

In [ ]:
trip_distance_dim = trip_distance_dim[['trip_distance_id','trip_distance']]

In [ ]:
pickup_location_dim = df[['pickup_latitude','pickup_longitude']].drop_duplicates().reset_index(drop=True)

In [ ]:
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index

In [ ]:
pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']]

In [ ]:
dropoff_location_dim = df[['dropoff_latitude','dropoff_longitude']].drop_duplicates().reset_index(drop=True)

In [ ]:
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index

In [ ]:
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]

In [ ]:
dropoff_location_dim

       dropoff_location_id  dropoff_latitude  dropoff_longitude
0                        0         40.746128         -74.004265
1                        1         40.733166         -74.005943
2                        2         40.675770         -73.974541
3                        3         40.757767         -73.969650
4                        4         40.695053         -74.177170
...                    ...               ...                ...
98412                98412         40.750462         -73.998245
98413                98413         40.752529         -73.982361
98414                98414         40.770512         -73.865028
98415                98415         40.759148         -73.970695
98416                98416         40.754910         -73.980354

[98417 rows x 3 columns]

In [ ]:
rate_code_dim = df['RatecodeID'].drop_duplicates().reset_index(drop=True)

In [ ]:
rate_code_dim = rate_code_dim.to_frame(name='RatecodeID')

In [ ]:
rate_code_name = {
    1 : 'Standard rate',
    2 : 'JFK',
    3 : 'Newark',
    4 : 'Nassau or Westchester',
    5 : 'Negotiated fare',
    6 : 'Group ride',
    99 : 'Null/unknown'

}

In [ ]:
rate_code_dim['RateCode_name'] = rate_code_dim['RatecodeID'].map(rate_code_name)

In [ ]:
rate_code_dim['rate_code_id'] = rate_code_dim.index

In [ ]:
rate_code_dim = rate_code_dim[['rate_code_id','RatecodeID','RateCode_name']]

In [ ]:
rate_code_dim

   rate_code_id  RateCode          RateCode_name
0             0         1          Standard rate
1             1         3                 Newark
2             2         2                    JFK
3             3         5        Negotiated fare
4             4         4  Nassau or Westchester
5             5         6             Group ride

In [ ]:
payment_type_dim = df['payment_type'].drop_duplicates().reset_index(drop=True)

In [ ]:
payment_type_dim = payment_type_dim.to_frame(name='payment_type')

In [ ]:
payment_type_dim['payment_type_id'] = payment_type_dim.index

In [ ]:
payment_type_name = {
    0 : 'Flex Fare trip',
    1 : 'Credit card',
    2 : 'Cash',
    3 : 'No charge',
    4 : 'Dispute',
    5 : 'Unknown',
    6 : 'Voided trip'
}

In [ ]:
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)

In [ ]:
payment_type_dim = payment_type_dim[['payment_type_id','payment_type','payment_type_name']]

In [ ]:
payment_type_dim

   payment_type_id  payment_type payment_type_name
0                0             1       Credit card
1                1             2              Cash
2                2             3         No charge
3                3             4           Dispute

In [ ]:
taxi_fact_table = df.merge(pickup_location_dim, on=['pickup_latitude','pickup_longitude'], how='left') \
                    .merge(dropoff_location_dim, on=['dropoff_latitude','dropoff_longitude'], how='left') \
                    .merge(datetime_dim, on=['tpep_pickup_datetime','tpep_dropoff_datetime'], how='left') \
                    .merge(trip_distance_dim, on='trip_distance', how='left') \
                    .merge(rate_code_dim, on='RatecodeID', how='left') \
                    .merge(payment_type_dim, on='payment_type', how='left') \
                    [['VendorID','datetime_id','rate_code_id','payment_type_id','pickup_location_id','dropoff_location_id','trip_distance_id','passenger_count','fare_amount','extra','mta_tax','tip_amount','tolls_amount','improvement_surcharge','total_amount']]

In [ ]:
taxi_fact_table

,VendorID,datetime_id,rate_code_id,payment_type_id,pickup_location_id,dropoff_location_id,trip_distance_id,passenger_count,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,0,0,0,0,0,0,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,0,0,1,1,1,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,0,0,2,2,2,2,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,3,0,0,3,3,3,3,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,3,1,0,4,4,4,5,98.0,0.0,0.0,0.00,15.50,0.3,113.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,99848,0,1,98050,98412,19,1,5.0,0.0,0.5,0.00,0.00,0.3,5.80
99996,1,99849,0,0,98051,98413,71,1,14.0,0.0,0.5,2.00,0.00,0.3,16.80
99997,1,99850,0,0,98052,98414,295,1,29.0,0.0,0.5,8.80,5.54,0.3,44.14
99998,2,99851,0,0,98053,98415,152,1,5.5,0.5,0.5,1.36,0.00,0.3,8.16
99999,1,99852,0,1,98054,98416,29,1,6.0,0.0,0.5,0.00,0.00,0.3,6.80